   _____ _    _ _   _ ____  _    _ _____  _   _ 
  / ____| |  | | \ | |  _ \| |  | |  __ \| \ | |
 | (___ | |  | |  \| | |_) | |  | | |__) |  \| |
  \___ \| |  | | . ` |  _ <| |  | |  _  /| . ` |
  ____) | |__| | |\  | |_) | |__| | | \ \| |\  |
 |_____/ \____/|_| \_|____/ \____/|_|  \_\_| \_|

# Main plugin configuration

cooldown-tick-period: 60
# Ticks: 20 - 100
# Defines how frequently the sun strikes
# CAUTION! May reduce performance on lower values!

burning-duration: 100
# Ticks: 0 - 500
# Defines how long the player will burn after each sun strike
# BE AWARE - if player is already burning, this may do nothing

sun-burn-mode: SKYLIGHT
# Mode: SKYLIGHT / ANYLIGHT / MATERIALCONFIG
# Defines how plugin decides if the player is in shadow
# ---
# SKYLIGHT
# Only sky light level matters
# This is set by default
# ---
# ANYLIGHT
# Any light source matters
# This may be too much, be careful
# ---
# MATERIALCONFIG
# Now player is in shadow if there is any opaque block above him
# If all blocks above the player are transparent - he is exposed to the sun strike
# You can change which block is transparent manually (check 'settings' folder)
# In this folder there are 'transparent-materials.yml' and 'transparent-tags.yml'
# ---

min-light-level: 15
# Integer: 0 - 16
# Defines the minimum level of light required to damage the player
# If set to 16 - it never damages; if set to 0 - it damages anywhere
# This parameter does nothing if MATERIALCONFIG mode is set

player-damage: 0
# Integer: 0 - 100
# Defines how much damage player will receive on each sun strike
# BE AWARE - this is direct damage, it does not include potential damage by fire

helmet-damage: 1
# Integer: 0 - 50
# Defines how much damage equipped helmet will receive on each sun strike
# You can manually change list of items that are considered as helmets ('settings' folder)
# In this folder there is "helmet-materials.yml', check its content

non-helmet-drop-chance: 3.5
# Percentage: 0 - 100 (may be decimal, up to 4 digits accuracy)
# Defines how likely equipped non-helmet will drop on each sun strike
# If less than 0 - any non-helmet item (pumkin, player's head, etc.) does not defend from the sun!
# If set to 0 - any non-helmet item defends from the sun unless taken off
# You can manually change list of items that are considered as 'non-protecting' ('settings' folder)
# In this folder there is "helmet-materials.yml', check its content
# Items marked as 'non-protecting' WILL NOT defend from the sun, even if this config is enabled
# Such items will not be dropped from the head slot either (no matter what the drop chance is)
# Items marked as 'perm-protecting' WILL defend from the sun and have no chance to be dropped

water-defence: false
# Boolean: true / false
# Permanently blocks any sun damage if player is in water
