name: SunBurn
api: Plugin
main: com.danmor.Plugin
version: 1.0.0-SNAPSHOT
author: danmor
api-version: 1.21
description: SunBurn minecraft java plugin. Feel yourself a zombie! Kinda...

commands:
  sunburn:
    description: "Make the sun dangerous!"
    usage: "Usage: /sunburn <on|off|reload|status>"